import prisma from "../lib/prisma";
import bcrypt from "bcryptjs";

async function main() {
  console.log("🌱 Seeding database...");

  // Seed Admin User
  const passwordHash = await bcrypt.hash("admin123", 12);

  await prisma.adminUser.upsert({
    where: { email: "admin@blob.jo" },
    update: {},
    create: {
      email: "admin@blob.jo",
      passwordHash,
      name: "مدير النظام",
      role: "super_admin",
      isActive: true,
    },
  });
  console.log("✅ Admin user created: admin@blob.jo / admin123");

  // Seed Categories
  const categories = [
    {
      name: "هوديز",
      nameEn: "Hoodies",
      slug: "hoodies",
      description: "هوديز قطنية عالية الجودة مع تصاميم مخصصة",
      sortOrder: 1,
    },
    {
      name: "تيشيرتات",
      nameEn: "T-Shirts",
      slug: "tshirts",
      description: "تيشيرتات قطنية مريحة بتصاميم فريدة",
      sortOrder: 2,
    },
    {
      name: "أكواب",
      nameEn: "Mugs",
      slug: "mugs",
      description: "أكواب سيراميك مع طباعة عالية الجودة",
      sortOrder: 3,
    },
    {
      name: "ملصقات",
      nameEn: "Stickers",
      slug: "stickers",
      description: "ملصقات فينيل مقاومة للماء",
      sortOrder: 4,
    },
  ];

  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: category,
      create: category,
    });
  }
  console.log(`✅ Seeded ${categories.length} categories`);

  // Get created categories
  const hoodiesCategory = await prisma.category.findUnique({ where: { slug: "hoodies" } });
  const tshirtsCategory = await prisma.category.findUnique({ where: { slug: "tshirts" } });
  const mugsCategory = await prisma.category.findUnique({ where: { slug: "mugs" } });

  // Seed Products
  const products = [
    // Anime Hoodies
    {
      name: "Naruto",
      nameAr: "هودي ناروتو",
      slug: "naruto-hoodie",
      description: "Anime Hoodie - Naruto",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", "كحلي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Naruto.png",
      isFeatured: true, // bestseller in old code
      allowCustomDesign: false,
    },
    {
      name: "One Piece Black",
      nameAr: "هودي ون بيس أسود",
      slug: "one-piece-black",
      description: "Anime Hoodie - One Piece",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/One%20piece%20black.png",
      allowCustomDesign: false,
    },
    {
      name: "One Piece",
      nameAr: "هودي ون بيس",
      slug: "one-piece-hoodie",
      description: "Anime Hoodie - One Piece",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", "كحلي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/One%20piece.png",
      allowCustomDesign: false,
    },
    {
      name: "One Piece White",
      nameAr: "هودي ون بيس أبيض",
      slug: "one-piece-white",
      description: "Anime Hoodie - One Piece",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/onepeice%20white.png",
      isFeatured: true, // new in old code
      allowCustomDesign: false,
    },

    // Movie Hoodies
    {
      name: "Batman Black",
      nameAr: "هودي باتمان أسود",
      slug: "batman-black",
      description: "Movie Hoodie - Batman",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Batman%20Black.png",
      allowCustomDesign: false,
    },
    {
      name: "Batman White",
      nameAr: "هودي باتمان أبيض",
      slug: "batman-white",
      description: "Movie Hoodie - Batman",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Batman%20White.png",
      allowCustomDesign: false,
    },
    {
      name: "Harry Potter",
      nameAr: "هودي هاري بوتر",
      slug: "harry-potter-hoodie",
      description: "Movie Hoodie - Harry Potter",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", "كحلي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Harry%20Potter.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Spider-Man",
      nameAr: "هودي سبايدر مان",
      slug: "spider-man-hoodie",
      description: "Movie Hoodie - Spider-Man",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "أحمر"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Spider-man%20hoodie.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Minecraft",
      nameAr: "هودي ماينكرافت",
      slug: "minecraft-hoodie",
      description: "Gaming Hoodie - Minecraft",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", " أخضر"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/minecraft%20front.png",
      allowCustomDesign: false,
    },

    // Series Hoodies
    {
      name: "Friends Black",
      nameAr: "هودي فريندز أسود",
      slug: "friends-black",
      description: "Series Hoodie - Friends",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/frends%20hoodie%20black.png",
      allowCustomDesign: false,
    },
    {
      name: "Friends Hoodie",
      nameAr: "هودي فريندز",
      slug: "friends-hoodie-main",
      description: "Series Hoodie - Friends",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Friends%20hoodie%20black.%20.png",
      allowCustomDesign: false,
    },
    {
      name: "Friends Classic",
      nameAr: "هودي فريندز كلاسيك",
      slug: "friends-classic",
      description: "Series Hoodie - Friends",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/frinends%20hoodie%20black.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Game of Thrones",
      nameAr: "هودي صراع العروش",
      slug: "got-hoodie",
      description: "Series Hoodie - Game of Thrones",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Game%20of%20Thrones.png",
      allowCustomDesign: false,
    },
    {
      name: "GOT Quote",
      nameAr: "هودي اقتباس صراع العروش",
      slug: "got-quote",
      description: "Series Hoodie - Game of Thrones Quote",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Game%20of%20ThronesQuote%20.png",
      allowCustomDesign: false,
    },
    {
      name: "Stranger Things",
      nameAr: "هودي أشياء غريبة",
      slug: "stranger-things-hoodie",
      description: "Series Hoodie - Stranger Things",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Stranger%20things%20Hoodie.png",
      allowCustomDesign: false,
    },
    {
      name: "Breaking Bad",
      nameAr: "هودي بريكنج باد",
      slug: "breaking-bad-hoodie",
      description: "Series Hoodie - Breaking Bad",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Breaking%20Bad.png",
      allowCustomDesign: false,
    },
    {
      name: "I Am The Danger",
      nameAr: "هودي أنا الخطر",
      slug: "breaking-bad-danger",
      description: "Series Hoodie - Breaking Bad",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/I'm%20not%20a%20danger,%20I%20am%20the%20danger.png",
      allowCustomDesign: false,
    },
    {
      name: "Say My Name",
      nameAr: "هودي قل اسمي",
      slug: "breaking-bad-say-my-name",
      description: "Series Hoodie - Breaking Bad",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Say%20my%20name.png",
      allowCustomDesign: false,
    },

    // Sports Hoodies
    {
      name: "Barcelona Black",
      nameAr: "هودي برشلونة أسود",
      slug: "barcelona-black",
      description: "Sports Hoodie - Barcelona",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Barcelona%20Black.png",
      allowCustomDesign: false,
    },
    {
      name: "Barcelona White",
      nameAr: "هودي برشلونة أبيض",
      slug: "barcelona-white",
      description: "Sports Hoodie - Barcelona",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Barcelona%20White.png",
      allowCustomDesign: false,
    },
    {
      name: "Real Madrid",
      nameAr: "هودي ريال مدريد",
      slug: "real-madrid-hoodie",
      description: "Sports Hoodie - Real Madrid",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Real%20Madrid.png",
      allowCustomDesign: false,
    },
    {
      name: "Real Madrid Kit",
      nameAr: "هودي طقم ريال مدريد",
      slug: "real-madrid-kit",
      description: "Sports Hoodie - Real Madrid",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Real%20Madrid%20kit.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "CR7",
      nameAr: "هودي كريستيانو رونالدو",
      slug: "cr7-hoodie",
      description: "Sports Hoodie - Cristiano Ronaldo",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/CR7%20front.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Messi",
      nameAr: "هودي ميسي",
      slug: "messi-hoodie",
      description: "Sports Hoodie - Messi",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/messi%20front.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Mercedes F1 Black",
      nameAr: "هودي مرسيدس F1 أسود",
      slug: "mercedes-f1-black",
      description: "Sports Hoodie - Mercedes F1",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Mercedes%20f1.png",
      allowCustomDesign: false,
    },
    {
      name: "Mercedes F1 White",
      nameAr: "هودي مرسيدس F1 أبيض",
      slug: "mercedes-f1-white",
      description: "Sports Hoodie - Mercedes F1",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Mercedes%20white.png",
      allowCustomDesign: false,
    },
    {
      name: "Red Bull F1",
      nameAr: "هودي ريد بول F1",
      slug: "red-bull-f1",
      description: "Sports Hoodie - Red Bull F1",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["كحلي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Redbull%20f1.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Jordan Team",
      nameAr: "هودي منتخب الأردن",
      slug: "jordan-team",
      description: "Sports Hoodie - Jordan National Team",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أبيض", "أحمر", "أسود"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/JordanTeam.png",
      allowCustomDesign: false,
    },
    {
      name: "Palestine",
      nameAr: "هودي فلسطين",
      slug: "palestine-hoodie",
      description: "Hoodie - Palestine",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      image: "/images/Palestine%20Front.png",
      isFeatured: true,
      allowCustomDesign: false,
    },

    // Mugs
    {
      name: "Anime Mug",
      nameAr: "كوب أنمي",
      slug: "anime-mug",
      description: "Mug - Anime",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/anime%20mug.png",
      allowCustomDesign: false,
    },
    {
      name: "Baby Yoda Mug",
      nameAr: "كوب بيبي يودا",
      slug: "baby-yoda-mug",
      description: "Mug - Baby Yoda",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/baby%20yuda%20mug.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Batman Mug",
      nameAr: "كوب باتمان",
      slug: "batman-mug",
      description: "Mug - Batman",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/batman%20mug.png",
      allowCustomDesign: false,
    },
    {
      name: "Friends Mug",
      nameAr: "كوب فريندز",
      slug: "friends-mug",
      description: "Mug - Friends",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/friends%20mug.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Heisenberg Mug",
      nameAr: "كوب هايزنبرج",
      slug: "heisenberg-mug",
      description: "Mug - Breaking Bad",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/Heisenberg%20Mug.png",
      allowCustomDesign: false,
    },
    {
      name: "Hellfire Mug",
      nameAr: "كوب نادي الجحيم",
      slug: "hellfire-mug",
      description: "Mug - Stranger Things",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/Hellfire%20mug.png",
      isFeatured: true,
      allowCustomDesign: false,
    },
    {
      name: "Quote Mug",
      nameAr: "كوب اقتباس",
      slug: "quote-mug-generic",
      description: "Mug - Quote",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/quote%20mug.png",
      allowCustomDesign: false,
    },
    {
      name: "Stranger Things Mug",
      nameAr: "كوب أشياء غريبة",
      slug: "stranger-things-mug",
      description: "Mug - Stranger Things",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/Stranger%20things%20mug.png",
      allowCustomDesign: false,
    },
    {
      name: "Stranger Things Red Mug",
      nameAr: "كوب أشياء غريبة أحمر",
      slug: "stranger-things-red-mug",
      description: "Mug - Stranger Things",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      image: "/images/Stranger%20thingsred%20mug.png",
      allowCustomDesign: false,
    },

    // Original Seed Products
    {
      name: "هودي وطن",
      nameAr: "هودي وطن",
      slug: "watan-hoodie",
      description: "هودي قطني فاخر مع خط عربي مميز - تصميم وطني أردني",
      price: 15,
      compareAtPrice: 45,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", "كحلي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      isFeatured: true,
      allowCustomDesign: true,
      image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "هودي عمّان",
      nameAr: "هودي عمّان",
      slug: "amman-hoodie",
      description: "هودي بتصميم مدينة عمّان - أظهر حبك للعاصمة",
      price: 15,
      categoryId: hoodiesCategory?.id,
      colors: ["أسود", "أبيض", "زيتي"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      isFeatured: false,
      allowCustomDesign: true,
      image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "تيشيرت كلاسيك",
      nameAr: "تيشيرت كلاسيك",
      slug: "classic-tshirt",
      description: "تيشيرت قطني مريح للاستخدام اليومي",
      price: 15,
      compareAtPrice: 15,
      categoryId: tshirtsCategory?.id,
      colors: ["أسود", "أبيض", "رمادي", "كحلي", "أحمر"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      isActive: true,
      isFeatured: true,
      allowCustomDesign: true,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "كوب اقتباس عربي",
      nameAr: "كوب اقتباس عربي",
      slug: "arabic-quote-mug",
      description: "كوب سيراميك بتصميم خط عربي جميل",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض", "أسود"],
      sizes: ["Standard"],
      isActive: true,
      isFeatured: true,
      allowCustomDesign: true,
      image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80",
    },
    {
      name: "كوب مخصص",
      nameAr: "كوب مخصص",
      slug: "custom-mug",
      description: "صمم كوبك الخاص بالصور والنصوص التي تريدها",
      price: 2,
      categoryId: mugsCategory?.id,
      colors: ["أبيض"],
      sizes: ["Standard"],
      isActive: true,
      isFeatured: false,
      allowCustomDesign: true,
      image: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=800&q=80",
    },
  ];

  for (const product of products) {
    // Generate variants
    const variants = [];
    for (const color of product.colors) {
      for (const size of product.sizes) {
        variants.push({
          color,
          size,
          stock: Math.floor(Math.random() * 50) + 10, // Random stock between 10 and 60
          sku: `${product.slug}-${color}-${size}`.toUpperCase(),
          isActive: true
        });
      }
    }

    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {
        name: product.name,
        nameAr: product.nameAr,
        description: product.description,
        price: product.price,
        compareAtPrice: product.compareAtPrice,
        categoryId: product.categoryId,
        colors: JSON.stringify(product.colors),
        sizes: JSON.stringify(product.sizes),
        isActive: product.isActive,
        isFeatured: product.isFeatured,
        allowCustomDesign: product.allowCustomDesign,
      },
      create: {
        name: product.name,
        nameAr: product.nameAr,
        slug: product.slug,
        description: product.description,
        price: product.price,
        compareAtPrice: product.compareAtPrice,
        categoryId: product.categoryId,
        colors: JSON.stringify(product.colors),
        sizes: JSON.stringify(product.sizes),
        isActive: product.isActive,
        isFeatured: product.isFeatured,
        allowCustomDesign: product.allowCustomDesign,
        variants: {
          create: variants
        },
        images: {
          create: [{ url: product.image, isPrimary: true, altText: product.name }]
        }
      },
    });
  }
  console.log(`✅ Seeded ${products.length} products with variants`);

  // Seed Settings
  const settings = [
    { key: "store_name", value: "BloB.JO", type: "string", group: "general" },
    { key: "store_name_ar", value: "بلوب", type: "string", group: "general" },
    { key: "contact_phone", value: "+962791234567", type: "string", group: "contact" },
    { key: "contact_email", value: "info@blob.jo", type: "string", group: "contact" },
    { key: "contact_instagram", value: "@blob.jo", type: "string", group: "contact" },
    { key: "contact_whatsapp", value: "+962791234567", type: "string", group: "contact" },
    { key: "delivery_amman", value: "0", type: "number", group: "shipping" },
    { key: "delivery_outside", value: "0", type: "number", group: "shipping" },
    { key: "free_shipping_threshold", value: "50", type: "number", group: "shipping" },
    { key: "meta_title", value: "BloB.JO - طباعة حسب الطلب في الأردن", type: "string", group: "seo" },
    { key: "meta_description", value: "أنشئ منتجات مخصصة بتصميمك الخاص - هوديز، تيشيرتات، أكواب وأكثر", type: "string", group: "seo" },
  ];

  for (const setting of settings) {
    await prisma.setting.upsert({
      where: { key: setting.key },
      update: { value: setting.value, type: setting.type, group: setting.group },
      create: setting,
    });
  }
  console.log(`✅ Seeded ${settings.length} settings`);

  // Seed Homepage Sections
  const sections = [
    {
      sectionKey: "hero",
      title: "حوّل أفكارك إلى واقع",
      titleAr: "حوّل أفكارك إلى واقع",
      subtitle: "صمم منتجاتك الخاصة بسهولة واحصل عليها بجودة عالية",
      subtitleAr: "صمم منتجاتك الخاصة بسهولة واحصل عليها بجودة عالية",
      ctaText: "ابدأ الآن",
      ctaTextAr: "ابدأ الآن",
      ctaLink: "/products",
      isActive: true,
      sortOrder: 1,
    },
    {
      sectionKey: "featured_products",
      title: "منتجات مميزة",
      titleAr: "منتجات مميزة",
      subtitle: "اكتشف أحدث تصاميمنا",
      subtitleAr: "اكتشف أحدث تصاميمنا",
      isActive: true,
      sortOrder: 2,
    },
    {
      sectionKey: "how_it_works",
      title: "كيف يعمل؟",
      titleAr: "كيف يعمل؟",
      subtitle: "أربع خطوات بسيطة للحصول على منتجك المخصص",
      subtitleAr: "أربع خطوات بسيطة للحصول على منتجك المخصص",
      isActive: true,
      sortOrder: 3,
    },
  ];

  for (const section of sections) {
    await prisma.homepageSection.upsert({
      where: { sectionKey: section.sectionKey },
      update: section,
      create: section,
    });
  }
  console.log(`✅ Seeded ${sections.length} homepage sections`);

  // Seed FAQs
  const faqs = [
    {
      question: "How long does delivery take?",
      questionAr: "كم يستغرق وقت التوصيل؟",
      answer: "Delivery takes 2-4 business days within Amman, and 3-5 days for other cities.",
      answerAr: "التوصيل يستغرق 2-4 أيام عمل داخل عمّان، و3-5 أيام لباقي المحافظات.",
      category: "shipping",
      sortOrder: 1,
    },
    {
      question: "What payment methods do you accept?",
      questionAr: "ما هي طرق الدفع المتاحة؟",
      answer: "We accept cash on delivery and bank transfers.",
      answerAr: "نقبل الدفع نقداً عند الاستلام والتحويل البنكي.",
      category: "payment",
      sortOrder: 2,
    },
    {
      question: "Can I return or exchange products?",
      questionAr: "هل يمكنني إرجاع أو استبدال المنتجات؟",
      answer: "Custom products cannot be returned unless there's a manufacturing defect.",
      answerAr: "المنتجات المخصصة لا يمكن إرجاعها إلا في حالة وجود عيب تصنيعي.",
      category: "general",
      sortOrder: 3,
    },
  ];

  for (const faq of faqs) {
    await prisma.fAQ.create({
      data: faq,
    });
  }
  console.log(`✅ Seeded ${faqs.length} FAQs`);

  console.log("🎉 Database seeding completed!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
